# Generated by Django 4.1.3 on 2022-11-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='desription',
            new_name='description',
        ),
    ]
